_format_version: "3.0"
services:
- host: kongair-routes
  id: 5bbc0ad8-3b7c-5dfe-a676-b28f30523a6f
  name: routes-service
  path: /
  plugins:
  - name: key-auth
    config:
      key_names:
      - apikey
  - name: rate-limiting
    config:
      minute: 5
      policy: local
  - name: file-log
    config:
      path: "/tmp/logs/file.log"
  port: 8081
  protocol: http
  routes:
  - id: 4da7a5e5-9e69-59af-a6c3-46a675c5bac6
    methods:
    - GET
    name: routes-service_health_get
    paths:
    - ~/api/v1/routes/health$
    plugins:
    - name: request-transformer
      config:
        replace:
          uri: /health
    regex_priority: 200
    strip_path: false
    tags: []
  - id: 89f28ad3-74db-5149-8fa5-f7fffbfda79c
    methods:
    - GET
    name: routes-service_get-routes
    paths:
    - ~/api/v1/routes$
    plugins:
    - name: request-transformer
      config:
        replace:
          uri: /routes
    regex_priority: 200
    strip_path: false
    tags: []
  - id: 831bf89a-08be-5dbd-bcd2-aa2348d784d3
    methods:
    - GET
    name: routes-service_get-route
    paths:
    - ~/api/v1/routes/(?<id>[^#?/]+)$
    plugins:
    - name: request-transformer
      config:
        replace:
          uri: /routes/$(uri_captures["id"])
    regex_priority: 100
    strip_path: false
    tags: []
  tags: []
upstreams: []
